### ISSUE TITLE
ライセンスを明記してほしい

### ISSUE THREAD

**Issue by gfx** [msakuta/rusty-programmer#2]
はじめまして、『 Rustで作るプログラミング言語 』を楽しく読ませていただいております。

ところで、この本に奮起されて私も自分用のちょっとした言語を作り始めました。そこでは少なくない部分をこの本のコードをそのまま使っているのですが、このプロジェクトにライセンスが明記されていないことに気づきました。ライセンスのないコードを使ったり参考にしたりするわけにはいきませんので、つきましては何かライセンス（できればオープンソースライセンス）を明記していただけないでしょうか。

よろしくお願いいたします。

**Comment by msakuta** [comment]
拙著を楽しく読んでいただいてありがとうございます。

ご指摘の通り、ライセンスは明示していませんでした。

最も使いやすいかと思いますので、MITライセンスとします。

良い言語ができるとよいですね！！

**Comment by gfx** [comment]
ありがとうございます！

MITライセンスであれば安心して再利用できます。
