### ISSUE TITLE
05a-pestのコンパイルがうまくできません。

### ISSUE THREAD

**Issue by m1goh** [msakuta/rusty-programmer#5]
pestを使用した構文解析のサンプルがうまくコンパイルできません。
Cargo.tomlにクレートとマクロのバージョンを記述して、Cargo runしましたがかなりのエラーがでてきてしまいます。

"""akiyoshi@beetle03:~/my_rust/ruscal05a2$ cat Cargo.toml
[package]
name = "ruscal05a2"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = "2.7.11"
pest_derive = "2.7.11"
”””
クレートの指定はこれでいいと思いますが
extern create pest_deriveしているマクロの指定は自信がありません。

どこを直してあげたらコンパイルできるか教えて下さい。よろしくお願いします。

**Comment by msakuta** [comment]
自前でクレートを立てたのですね。

実際のコードは載せられますか？またエラーメッセージの一部でもよいのでコピペできますか？ Cargo.toml で見れる範囲では問題は見当たりません。

**Comment by m1goh** [comment]
sakutaさん、返信ありがとうございます。

examples/expr.pestが読めるようにパッケージの階層構造を変更してcargo runを実行して無事コンパイルできました。
お騒がせしました。
